apiVersion: v2
name: basic-chart
description: A Helm chart for deploying an app with configurable persistence, ingress, configmap/secret env vars, extra Kubernetes objects, and a Horizontal Pod Autoscaler (HPA)
type: application
version: 0.5.0
appVersion: "1.0"
