{{- if and .Values.secret.enabled (not .Values.secret.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "basic-chart.fullname" . }}-secret
  labels:
    {{- include "basic-chart.labels" . | nindent 4 }}
type: {{ default "Opaque" .Values.secret.type }}
stringData:
{{ toYaml .Values.secret.stringData | indent 2 }}
{{- end }}
